# Generated by Django 4.0.4 on 2022-05-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=30)),
                ('designation', models.CharField(max_length=50)),
                ('addr', models.TextField(max_length=100)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
