# Generated by Django 4.0.4 on 2022-06-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApi', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='emp',
        ),
        migrations.AddField(
            model_name='employee',
            name='proj',
            field=models.ManyToManyField(related_name='project', to='employeeApi.project'),
        ),
    ]
