# Generated by Django 4.0.4 on 2022-06-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApi', '0003_remove_project_emp_employee_proj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='proj',
        ),
        migrations.AddField(
            model_name='project',
            name='emp',
            field=models.ManyToManyField(to='employeeApi.employee'),
        ),
    ]
