# Generated by Django 4.0.4 on 2022-06-03 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20)),
                ('duration', models.IntegerField()),
                ('pattern', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=70)),
                ('rollno', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('mob', models.CharField(max_length=10)),
            ],
        ),
    ]
