# Generated by Django 4.0.4 on 2022-06-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApi', '0002_alter_student_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cname',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='mob',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
