# Generated by Django 4.0.4 on 2022-06-03 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentApi', '0005_remove_student_course_delete_course_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=20, unique=True)),
                ('duration', models.IntegerField()),
                ('pattern', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=70)),
                ('rollno', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.DateField()),
                ('mob', models.CharField(max_length=10, unique=True)),
                ('course', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentApi.course')),
            ],
        ),
    ]
