# Generated by Django 4.0.4 on 2022-06-03 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentApi', '0008_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentApi.course'),
        ),
    ]
