# Generated by Django 4.0.4 on 2022-06-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
    ]
