# Generated by Django 4.0.4 on 2022-06-04 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mob', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=50)),
                ('pin', models.CharField(max_length=6)),
                ('product', models.ManyToManyField(to='productApi.product')),
            ],
        ),
    ]
